[package]
name = "zk-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = { path = "bls12_381" }
subtle = "2.4"
rand = {version = "0.8.5", features = ["small_rng"]}
